//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiNhaSach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebtReport
    {
        public int Id { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<decimal> FirstDebt { get; set; }
        public Nullable<decimal> LastDebt { get; set; }
        public Nullable<decimal> Arise { get; set; }
        public string MonthYear { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
