//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiNhaSach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodReceivedInfo
    {
        public int IDGoodReceived { get; set; }
        public int IDBook { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual GoodReceived GoodReceived { get; set; }
    }
}
