//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiNhaSach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentReceipt
    {
        public int ID { get; set; }
        public Nullable<int> IDCus { get; set; }
        public Nullable<System.DateTime> CreatAt { get; set; }
        public Nullable<decimal> AmountReceived { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
