//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiNhaSach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemValue
    {
        public Nullable<int> MinReceived { get; set; }
        public Nullable<int> MaxInventory { get; set; }
        public Nullable<decimal> MaxDebts { get; set; }
        public Nullable<int> MinSaleInventory { get; set; }
        public Nullable<double> Profit { get; set; }
        public Nullable<bool> DebtsPolicy { get; set; }
        public int ID { get; set; }
    }
}
